alohaDriver alohaFindT1T2.jq alohaSortSessions.jq: working input collection and verification for a single session

diff --git a/alohaDriver b/alohaDriver
--- a/alohaDriver
+++ b/alohaDriver
@@ -20,16 +20,16 @@
 # -a download AlohaInputs.json from the flywheel subject container 
 # -d download input files
 # -f Comma separated list of portions json collection to fake
-#    IgnoreBaselineT1NiftiTrimmedJson|IgnoreBaselineT1DicomJson|IgnoreBaselineT2NiftiJson|IgnoreBaselineT2DicomJson
-#    IgnoreBaselineT1LeftSegmentationJson|IgnoreBaselineT1RightSegmentationJson
-#    IgnoreBaselineAshsPmcT2JobId|IgnoreBaselineT2LeftSegmentationJson|IgnoreBaselineT2RightSegmentationJson
-#    RunBaselineT1Dcm2NiixGear|RunBaselineT1NecktrimGear|RunBaselineT2Dcm2NiixGear|RunAshsPmcT1Gear|RunBaselineAshsPmcT2Gear
+#    IgnoreBaselineAshsPmcT1JobId|IgnoreBaselineAshsPmcT2JobId
+#    IgnoreBaselineT1DicomJson|IgnoreBaselineT1LeftSegmentationJson|IgnoreBaselineT1NiftiTrimmedJson|IgnoreBaselineT1RightSegmentationJson
+#    IgnoreBaselineT2DicomJson|IgnoreBaselineT2LeftSegmentationJson|IgnoreBaselineT2NiftiJson|IgnoreBaselineT2RightSegmentationJson
+#    IgnoreFollowupT1DicomJson|IgnoreFollowupT1NiftiTrimmedJson|IgnoreFollowupT2DicomJson|IgnoreFollowupT2NiftiJson
 #
-#    IgnoreFollowupT1NiftiTrimmedJson|IgnoreFollowupT1DicomJson|IgnoreFollowupT2NiftiJson|IgnoreFollowupT2DicomJson
-#    RunFollowupT1Dcm2NiixGear|RunFollowupT1NecktrimGear|RunFollowupT2Dcm2NiixGear
-#    In order to run the BaselineT1NiftiNecktrimGear, you will have to ignore the BaselineT1NiftiTrimmedJson if there is any
+#    RunAshsPmcT1Gear|RunBaselineAshsPmcT2Gear
+#    RunBaselineT1Dcm2NiixGear|RunBaselineT1NecktrimGear
+#    RunBaselineT2Dcm2NiixGear|RunFollowupT1Dcm2NiixGear|RunFollowupT1NecktrimGear|RunFollowupT2Dcm2NiixGear
 #
-#        alohaDriver -f IgnoreBaselineT1NiftiTrimmedJson,RunBaselineT1Dcm2NiixGear -o stdout 66e4737e1b4b58bc3236d61d 
+#        alohaDriver -f RunBaselineT1Dcm2NiixGear,RunBaselineT2Dcm2NiixGear -o stdout 66e4737e1b4b58bc3236d61d 
 #
 # -n no-op
 # -o [site|stdout|none]
@@ -88,7 +88,9 @@ ProjectLabel=$(fwget -1 "$ProjectId" | jq -r '.label')
 GearTags='extra-large'
 FollowupDir="${TmpDir}/Followups"
 BaselineJsonFile="${TmpDir}/Baseline.json"
+BaselineDir="${TmpDir}/Baseline"
 
+[ -d "$BaselineDir" ] || mkdir -p "$BaselineDir"
 
 # *** should probbaly move all the intermediate file generation to the run portion of the driver
 
@@ -99,20 +101,22 @@ then
     
     # *** Don't need acquisition info as that will be in the T1/T2 stanzas
     BaselineJson=$(jq -r '.Baseline' "$SortedSessionsJsonFile")
-    if [ -z "$BaselineJson" ]
+    if [ -z "$BaselineJson" ] || [ "$BaselineJson" = 'null' ]
     then
     	echo "${CmdName} : Missing Baseline session" 1>&2
     	exit 2
     fi
 
-    FollowupCount=$(jq -r '.Followups | length' "$SortedSessionsJsonFile")
-    if [ 0 -ge "$FollowupCount" ]
+    FollowupCount=$(jq -r '[.Followups[] | select(.)] | length' "$SortedSessionsJsonFile")
+    # *** should make sure not all the followup sessions are null
+    if [ 0 -ge "$FollowupCount" ] 
     then
     	echo "${CmdName} : Missing Followup sessions" 1>&2
     	exit 3
     fi
     
     BaselineSessionId=$(echo "$BaselineJson" | jq -r '.SessionId')
+    BaselineSessionLabel=$(echo "$BaselineJson" | jq -r '.SessionLabel')
     BaselineSessionJsonFile="${TmpDir}/BaselineSession.json"
     jq -r '..|select(._id == "'"$BaselineSessionId"'")?' "$SubjectJsonFile" > "$BaselineSessionJsonFile"
     
@@ -141,16 +145,16 @@ then
     #   Set the AshsPmcT2JobId
     #
 
-    BaselineT1NiftiTrimmedJson=$(jq -r --argjson AlohaArgFlag '"-f"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and (.FileTags | any(. == "Trimmed")) ) ')
+    BaselineT1NiftiTrimmedJson=$(jq -r --argjson AlohaArgFlag '"-b"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and (.FileTags | any(. == "Trimmed")) ) ')
     if [ -z "$BaselineT1NiftiTrimmedJson" ] || [ "$BaselineT1NiftiTrimmedJson" = "null" ] || (echo "$opt_f" | grep -q -E 'IgnoreBaselineT1NiftiTrimmedJson|RunBaselineT1Dcm2NiixGear|RunBaselineT1NecktrimGear')
     then
-    	BaselineT1DicomJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( (.FileType == "archive") or (.FileType == "dicom") ) ')
-	if [ -z "$BaselineT1DicomJson" ] || (echo "$opt_f" | grep -q -E 'IgnoreBaselineT1DicomJson|RunBaselineT1Dcm2NiixGear|RunBaselineT1NecktrimGear')
+    	BaselineT1DicomJson=$(jq -r --argjson AlohaArgFlag '"-b"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( (.FileType == "archive") or (.FileType == "dicom") ) ')
+	if [ -z "$BaselineT1DicomJson" ] || (echo "$opt_f" | grep -q 'IgnoreBaselineT1DicomJson')
 	then
-	    echo "${CmdName} : Missing Baseline T1 for ${BaselineSessionLabel}(${BaselineSessionId}). Skipping" 1>&2
-	    BaselineT1NiftiJson='{ "Missing": true }'
+	    echo "${CmdName} : Missing Baseline T1 Dicom for ${BaselineSessionLabel}(${BaselineSessionId}). Skipping" 1>&2
+	    BaselineT1NiftiTrimmedJson='{ "Missing": true }'
 	else
-	    if (echo "$opt_f" | grep -q 'RunBaselineT1Dcm2NiixGear')
+	    if [ -z "$opt_f" ] || (echo "$opt_f" | grep -q 'RunBaselineT1Dcm2NiixGear')
 	    then
 		BaselineT1DicomFileId=$(echo "$BaselineT1DicomJson" | jq -r '.FileId')
 		BaselineT1Dicom2NiftiJobId=$(sys fwRunGear -w -t "$GearTags" -g dcm2niix -i dcm2niix_input "$BaselineT1DicomFileId")
@@ -168,10 +172,10 @@ then
 		BaselineT1DicomFileId=$(echo "$BaselineT1DicomJson" | jq -r '.FileId')
 		echo Faking fwRunGear -w -t "$GearTags" -g dcm2niix -i dcm2niix_input "$BaselineT1DicomFileId" 1>&2
 
-		BaselineT1NiftiFileId=$(jq -r --argjson AlohaArgFlag '"-f"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and ((.FileTags | any(. == "Trimmed")) | not) )' | jq -r '.FileId')
+		BaselineT1NiftiFileId=$(jq -r --argjson AlohaArgFlag '"-b"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and ((.FileTags | any(. == "Trimmed")) | not) )' | jq -r '.FileId')
 	    fi
 
-	    if (echo "$opt_f" | grep -q 'RunBaselineT1NecktrimGear')
+	    if [ -z "$opt_f" ] ||(echo "$opt_f" | grep -q 'RunBaselineT1NecktrimGear')
 	    then
 		BaselineT1NecktrimJobId=$(sys fwRunGear -w -t "$GearTags" -g 'necktrim' -i 'file' "$BaselineT1NiftiFileId")
     		if [ "$?" != 0 ]
@@ -185,25 +189,26 @@ then
 		BaselineT1NiftiTags=$(fwTag "$BaselineT1NiftiTrimmedFileId")
 		[ -n "$BaselineT1NiftiTags" ] && sys fwTag -q -t "$BaselineT1NiftiTags" "$BaselineT1NiftiTrimmedFileId"
 		
-		BaselineT1NiftiTrimmedJson=$(jq -r --argjson AlohaArgFlag '"-f"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and (.FileTags | any(. == "Trimmed")) ) ')
+		sys fwget -1 -raGz "$BaselineSessionId" > "$BaselineSessionJsonFile"
 	    else
 		echo Faking fwRunGear -w -t "$GearTags" -g 'necktrim' -i 'file' "$BaselineT1NiftiFileId" 1>&2
-		BaselineT1NiftiTrimmedJson=$(jq -r --argjson AlohaArgFlag '"-f"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and (.FileTags | any(. == "Trimmed")) ) ')
 	    fi
+
+	    BaselineT1NiftiTrimmedJson=$(jq -r --argjson AlohaArgFlag '"-b"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and (.FileTags | any(. == "Trimmed")) ) ')
 	fi
     fi
     BaselineT1NiftiTrimmedFileId=$(echo "$BaselineT1NiftiTrimmedJson" | jq -r '.FileId')
 
-    BaselineT2NiftiJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -s -r '[sort_by(.FileTimestamp) | .[] | select( .FileType == "nifti" ) ] | last' )
+    BaselineT2NiftiJson=$(jq -r --argjson AlohaArgFlag '"-c"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -s -r '[sort_by(.FileTimestamp) | .[] | select( .FileType == "nifti" ) ] | last' )
     if [ -z "$BaselineT2NiftiJson" ] || [ "$BaselineT2NiftiJson" = "null" ] || (echo "$opt_f" | grep -q -E 'IgnoreBaselineT2NiftiJson|RunBaselineT2Dcm2NiixGear')
     then
-    	BaselineT2DicomJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( (.FileType == "archive") or (.FileType == "dicom") ) ')
-	if [ -z "$BaselineT2DicomJson" ] || (echo "$opt_f" | grep -q IgnoreBaselineT2DicomJson)
+    	BaselineT2DicomJson=$(jq -r --argjson AlohaArgFlag '"-c"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( (.FileType == "archive") or (.FileType == "dicom") ) ')
+	if [ -z "$BaselineT2DicomJson" ] || (echo "$opt_f" | grep -q 'IgnoreBaselineT2DicomJson')
 	then
 	    echo "${CmdName} : Missing Baseline T2 for ${BaselineSessionLabel}(${BaselineSessionId}). Skipping" 1>&2
 	    BaselineT2NiftiJson='{ "Missing": true }'
 	else
-	    if (echo "$opt_f" | grep -q 'RunBaselineT2Dcm2NiixGear')
+	    if [ -z "$opt_f" ] || (echo "$opt_f" | grep -q 'RunBaselineT2Dcm2NiixGear')
 	    then
 		BaselineT2DicomFileId=$(echo "$BaselineT2DicomJson" | jq -r '.FileId')
 		BaselineT2Dicom2NiftiJobId=$(sys fwRunGear -w -t "$GearTags" -g dcm2niix -i dcm2niix_input "$BaselineT2DicomFileId")
@@ -218,12 +223,13 @@ then
 		BaselineT2DicomTags=$(fwTag "$BaselineT2DicomFileId")
 
 		[ -n "$BaselineT2DicomTags" ] && sys fwTag -q -t "$BaselineT2DicomTags" "$BaselineT2NiftiFileId"
+		sys fwget -1 -raGz "$BaselineSessionId" > "$BaselineSessionJsonFile"
 	    else
 		BaselineT2DicomFileId=$(echo "$BaselineT2DicomJson" | jq -r .'FileId')
 		echo Faking fwRunGear -w -t "$GearTags" -g dcm2niix -i dcm2niix_input "$BaselineT2DicomFileId" 1>&2
 	    fi
 
-	    BaselineT2NiftiJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( .FileType == "nifti" ) ' | jq -s -r ' sort_by(.FileTimestamp)  | last')
+	    BaselineT2NiftiJson=$(jq -r --argjson AlohaArgFlag '"-c"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile" | jq -r 'select( .FileType == "nifti" ) ' | jq -s -r ' sort_by(.FileTimestamp)  | last')
 	fi
     fi
     BaselineT2NiftiFileId=$(echo "$BaselineT2NiftiJson" | jq -r '.FileId')
@@ -231,7 +237,7 @@ then
     BaselineAshsPmcT1JobId=$( jq  -s -r '[ .[] | select( (.gear_info.name == "ashs") and (.detail.state == "complete") and (.config.config.ASHS_Atlases == "ASHS-PMC-T1") ) ] | sort_by(.created) | last | ._id' "$BaselineJobsJsonFile")
     if [ -z "$BaselineAshsPmcT1JobId" ] || [ "$BaselineAshsPmcT1JobId" = "null" ] || (echo "$opt_f" | grep -q -E 'IgnoreBaselineAshsPmcT1JobId|RunAshsPmcT1Gear')
     then
-	if (echo "$opt_f" | grep -q 'RunAshsPmcT1Gear')
+	if [ -z "$opt_f" ] || (echo "$opt_f" | grep -q 'RunAshsPmcT1Gear')
 	then
 	    BaselineAshsPmcT1JobId=$(fwRunGear -w -t "$GearTags" -g ashs -i T1w "$BaselineT1NiftiTrimmedFileId" -c '{"ASHS_Atlases": "ASHS-PMC-T1"}')
     	    if [ "$?" != 0 ]
@@ -271,9 +277,9 @@ then
     # Find the last ASHS PMC-T2 run on this session, and grab the JobId.
     #
     BaselineAshsPmcT2JobId=$(jq  -s -r '[ .[] | select( (.gear_info.name == "ashs") and (.detail.state == "complete") and (.config.config.ASHS_Atlases == "ASHS-PMC-T2") ) ] | sort_by(.created) | last | ._id' "$BaselineJobsJsonFile")
-    if [ -z "$BaselineAshsPmcT2JobId" ] || (echo "$opt_f" | grep -q -E 'IgnoreBaselineAshsPmcT2JobId|RunBaselineAshsPmcT2Gear' )
+    if [ -z "$BaselineAshsPmcT2JobId" ] || [ "$BaselineAshsPmcT2JobId" = 'null' ] || (echo "$opt_f" | grep -q -E 'IgnoreBaselineAshsPmcT2JobId|RunBaselineAshsPmcT2Gear' )
     then
-	if (echo "$opt_f" | grep -q 'RunBaselineAshsPmcT2Gear')
+	if [ -z "$opt_f" ] || (echo "$opt_f" | grep -q 'RunBaselineAshsPmcT2Gear')
 	then
 	    BaselineAshsPmcT2JobId=$(fwRunGear -w -t "$GearTags" -g ashs -i T1w "$BaselineT1NiftiTrimmedFileId" -i T2w "$BaselineT2NiftiFileId" -c '{"ASHS_Atlases": "ASHS-PMC-T2"}')
     	    if [ "$?" != 0 ]
@@ -363,15 +369,15 @@ then
         [ -n "$opt_v" ] && echo "FollowupSession = '${FollowupSessionLabel}(${FollowupSessionId})'" 1>&2
     
     	FollowupT1NiftiTrimmedJson=$(jq -r --argjson AlohaArgFlag '"-f"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and (.FileTags | any(. == "Trimmed")) ) ' | jq -s -r ' sort_by(.FileTimestamp)  | last' )
-	if [ -z "$FollowupT1NiftiTrimmedJson" ] || (echo "$opt_f" | grep -q -E 'IgnoreFollowupT1NiftiTrimmedJson|RunFollowupT1Dcm2NiixGear|RunFollowupT1NecktrimGear')
+	if [ -z "$FollowupT1NiftiTrimmedJson" ] || [ "$FollowupT1NiftiTrimmedJson" = 'null' ] || (echo "$opt_f" | grep -q -E 'IgnoreFollowupT1NiftiTrimmedJson|RunFollowupT1Dcm2NiixGear|RunFollowupT1NecktrimGear')
 	then
-    	    FollowupT1DicomJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile" | jq -r 'select( (.FileType == "archive") or (.FileType == "dicom") ) ' | jq -s -r ' sort_by(.FileTimestamp)  | last' )
-	    if [ -z "$FollowupT1DicomJson" ] || (echo "$opt_f" | grep -q 'IgnoreFollowupT1DicomJson')
+    	    FollowupT1DicomJson=$(jq -r --argjson AlohaArgFlag '"-f"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile" | jq -r 'select( (.FileType == "archive") or (.FileType == "dicom") ) ' | jq -s -r ' sort_by(.FileTimestamp)  | last' )
+	    if [ -z "$FollowupT1DicomJson" ] || [ "$FollowupT1DicomJson" = 'null' ] || (echo "$opt_f" | grep -q 'IgnoreFollowupT1DicomJson')
 	    then
 		echo "${CmdName} : Missing Followup T1 for ${FollowupSessionLabel}(${FollowupSessionId}). Skipping" 1>&2
 		FollowupT1NiftiJson='{ "Missing": true }'
 	    else
-		if (echo "$opt_f" | grep -q 'RunFollowupT1Dcm2NiixGear')
+		if [ -z "$opt_f" ] || (echo "$opt_f" | grep -q 'RunFollowupT1Dcm2NiixGear')
 		then
 		    FollowupT1DicomFileId=$(echo "$FollowupT1DicomJson" | jq -r '.FileId')
 		    FollowupT1Dicom2NiftiJobId=$(sys fwRunGear -w -t "$GearTags" -g dcm2niix -i dcm2niix_input "$FollowupT1DicomFileId")
@@ -394,7 +400,7 @@ then
 		fi
 	    fi
 	    
-	    if (echo "$opt_f" | grep -q 'RunFollowupT1NecktrimGear')
+	    if [ -z "$opt_f" ] || (echo "$opt_f" | grep -q 'RunFollowupT1NecktrimGear')
 	    then
 		    FollowupT1NecktrimJobId=$(sys fwRunGear -w -t "$GearTags" -g 'necktrim' -i 'file' "$FollowupT1NiftiFileId")
     		    if [ "$?" != 0 ]
@@ -407,26 +413,24 @@ then
 	    
 		FollowupT1NiftiTags=$(fwTag "$FollowupT1NiftiTrimmedFileId")
 		[ -n "$FollowupT1NiftiTags" ] && sys fwTag -q -t "$FollowupT1NiftiTags" "$FollowupT1NiftiTrimmedFileId"
-		
-		sys fwget -1 -raGz "$FollowupSessionId" > "$FollowupSessionJsonFile"
-
-		FollowupT1NiftiTrimmedJson=$(jq -r --argjson AlohaArgFlag '"-f"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and (.FileTags | any(. == "Trimmed")) ) ')
 	    else
 		echo Faking fwRunGear -w -t "$GearTags" -g 'necktrim' -i 'file' "$FollowupT1NiftiFileId" 1>&2
-		FollowupT1NiftiTrimmedJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and (.FileTags | any(. == "Trimmed")) ) '| jq -s -r ' sort_by(.FileTimestamp)  | last' )
 	    fi
+
+	    sys fwget -1 -raGz "$FollowupSessionId" > "$FollowupSessionJsonFile"
+	    FollowupT1NiftiTrimmedJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq "$FollowupSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and (.FileTags | any(. == "Trimmed")) ) '| jq -s -r ' sort_by(.FileTimestamp)  | last' )
 	fi
 
     	FollowupT2NiftiJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile" | jq -r 'select( .FileType == "nifti" ) '| jq -s -r ' sort_by(.FileTimestamp)  | last' )
 	if [ -z "$FollowupT2NiftiJson" ] || [ "$FollowupT2NiftiJson" = "null" ] || (echo "$opt_f" | grep -q -E 'IgnoreFollowupT2NiftiJson|RunFollowupT2Dcm2NiixGear')
 	then
     	    FollowupT2DicomJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile" | jq -r 'select( (.FileType == "archive") or (.FileType == "dicom") ) ' | jq -s -r ' sort_by(.FileTimestamp)  | last' )
-	    if [ -z "$FollowupT2DicomJson" ] || (echo "$opt_f" | grep -q 'IgnoreFollowupT2DicomJson')
+	    if [ -z "$FollowupT2DicomJson" ] || [ "$FollowupT2DicomJson" = 'null' ] || (echo "$opt_f" | grep -q 'IgnoreFollowupT2DicomJson')
 	    then
 		echo "${CmdName} : Missing Followup T2 for ${FollowupSessionLabel}(${FollowupSessionId}). Skipping" 1>&2
 		FollowupT2NiftiJson='{ "Missing": true }'
 	    else
-		if (echo "$opt_f" | grep -q 'RunFollowupT2Dcm2NiixGear')
+		if [ -z "$opt_f" ] || (echo "$opt_f" | grep -q 'RunFollowupT2Dcm2NiixGear')
 		then
 		    FollowupT2DicomFileId=$(echo "$FollowupT2DicomJson" | jq -r '.FileId')
 		    FollowupT2Dicom2NiftiJobId=$(sys fwRunGear -w -t "$GearTags" -g dcm2niix -i dcm2niix_input "$FollowupT2DicomFileId")
@@ -451,6 +455,7 @@ then
 		    echo Faking fwRunGear -w -t "$GearTags" -g dcm2niix -i dcm2niix_input "$FollowupT2DicomFileId" 1>&2
 		fi
 		
+		sys fwget -1 -raGz "$FollowupSessionId" > "$FollowupSessionJsonFile"
 		FollowupT2NiftiJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile" | jq -r 'select( .FileType == "nifti" ) ' | jq -s -r ' sort_by(.FileTimestamp)  | last' )
 	    fi
 	fi
@@ -633,4 +638,4 @@ exit
 #    https://stackoverflow.com/questions/32960857/how-to-convert-arbitrary-simple-json-to-csv-using-jq
 #
 jq -r -f alohaSessionReport.jq /tmp/aloharun.json | jq -f alohaFlattenDict.jq | jq -s -r '(.[0] | keys_unsorted) as $keys | $keys, map([.[ $keys[] ]])[] | @csv'
-p
+
