WIP

diff --git a/alohaDriver b/alohaDriver
--- a/alohaDriver
+++ b/alohaDriver
@@ -19,6 +19,9 @@
 #
 # -a download AlohaInputs.json from the flywheel subject container 
 # -d download input files
+# -f fake gear runs - comma separated list of job ids to use instead of actually running a gear
+#    T1Dcm2Niix,T1Necktrim,T2Dcm2Niix,AshsPmcT1,AshsPmcT2
+#    Gearnames are not case sensative
 # -n no-op
 # -o [site|stdout|none]
 #     create AlohaInputs.json and upload it to the flywheel site, print to stdout, neither
@@ -37,10 +40,10 @@ function sys {
     [ -n "$opt_n" ] || "$@"
 }
 
-while getopts adno:ruv arg
+while getopts adf:no:ruv arg
 do
 	case "$arg" in
-	     a|d|n|o|r|u|v)
+	     a|d|f|n|o|r|u|v)
 		eval "opt_${arg}='${OPTARG:=1}'"
 		;;
 	esac
@@ -73,6 +76,7 @@ SubjectLabel=$(jq -r '.label' "$SubjectJsonFile")
 Group=$(jq -r '.parents.group' "$SubjectJsonFile")
 ProjectId=$(jq -r '.parents.project' "$SubjectJsonFile")
 ProjectLabel=$(fwget -1 "$ProjectId" | jq -r '.label')
+GearTags='extra-large'
 
 if [ -n "$opt_o" ]
 then
@@ -98,59 +102,100 @@ then
     BaselineSessionJsonFile="${TmpDir}/BaselineSession.json"
     jq -r '..|select(._id == "'"$BaselineSessionId"'")?' "$SubjectJsonFile" > "$BaselineSessionJsonFile"
     
-    BaselineT1Json=$(jq -r --argjson AlohaArgFlag '"-b"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq "$BaselineSessionJsonFile" )
-    if [ -z "$BaselineT1Json" ] || [ "$BaselineT1Json" = "null" ]
-    then
-    	echo "${CmdName} : Missing baseline T1 acquisition" 1>&2
-    	exit 4
-    fi
-    
-    BaselineT2Json=$(jq -r --argjson AlohaArgFlag '"-c"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$BaselineSessionJsonFile")
-    if [ -z "$BaselineT2Json" ] || [ "$BaselineT2Json" = "null" ]
-    then
-    	echo "${CmdName} : Missing baseline T2 acquisition" 1>&2
-    	exit 5
-    fi
-    
     BaselineJobsJsonFile="${TmpDir}/BaselineJobs.json"
+    BaselineJobsJsonTmpFile="${TmpDir}/BaselineJobs.json.tmp"
     if [ ! \( \( -e "$BaselineJobsJsonFile" \) -a \( -s "$BaselineJobsJsonFile" \) \) ] || [ -n "$UpdateAll" ]
     then
 	# Need -r to get the output file id
-    	sys fwfind -1 -j -r session="$BaselineSessionId" > "$BaselineJobsJsonFile"
+    	sys fwfind -1 -j -r session="$BaselineSessionId" > "$BaselineJobsJsonTmpFile"
     	if [ "$?" != 0 ]
     	then
     		echo "${CmdName} : failed getting finding jobs for '$SessionLabel' ($SessionId)" 1>&2
     		exit 1
     	fi
+	[ -s "$BaselineJobsJsonTmpFile" ] && mv "$BaselineJobsJsonTmpFile" "$BaselineJobsJsonFile"
     fi
-    
-    BaselineT1LeftSegmentationJson=$(jq -s -r --argjson AlohaArgFlag '"-r"' --argjson Atlas '"ASHS-PMC-T1"' --argjson Handedness '"Left"' -f alohaFindSegmentFiles.jq "$BaselineJobsJsonFile")
-    if [ -z "$BaselineT1LeftSegmentationJson" ] || [ "$BaselineT1LeftSegmentationJson" = "null" ]
+
+    #
+    # Baseline extraction
+    # grab the most recent ashs PMC-T2 run
+    # If there is one,
+    #   Set the AshsPmcT2JobId and you have all the baseline inputs for aloha
+    # else
+    #   Find the T1 dicom, convert to nifti, necktrim, ashs-pmc-t1
+    #   Find the T2 dicom, convery to nifti, ashs-pmc-t2
+    #   Set the AshsPmcT2JobId
+    #
+
+    #
+    # Find the last ASHS PMC-T2 run on this session, and grab the JobId.
+    BaselineAshsPmcT2JobId=$(jq  -s -r '[ .[] | select( (.gear_info.name == "ashs") and (.detail.state == "complete") and (.config.config.ASHS_Atlases == "ASHS-PMC-T2") ) ] | sort_by(.created) | last | ._id' "$BaselineJobsJsonFile")
+    if [ -z "$BaselineAshsPmcT2JobId" ]
     then
-    	echo "${CmdName} : Missing baseline T1 Left segmentation file" 1>&2
-    	exit 6
+	true
+	#
+	# Then ashs PMC-T2 hasn't been run and we need to:
+	# Find a T1/T2 dicom AlohaInput in this session
+	# Convert T1/T2 dicom to nifti
+	# Necktrim T1 nifti
+	# Run ashs PMC-T1 on T1NiftiTrimmed
+	# Run ashs PMC-T2 on T1NiftiTrimmed and T2Nifti
+	# Set the BaselineAshsPmcT2JobId
     fi
     
-    BaselineT1RightSegmentationJson=$(jq -s -r --argjson AlohaArgFlag '"-s"' --argjson Atlas '"ASHS-PMC-T1"' --argjson Handedness '"Right"' -f alohaFindSegmentFiles.jq "$BaselineJobsJsonFile")
-    if [ -z "$BaselineT1RightSegmentationJson" ] || [ "$BaselineT1RightSegmentationJson" = "null" ]
-    then
-    	echo "${CmdName} : Missing baseline T1 Right segmentation file" 1>&2
-    	exit 7
-    fi
-    
-    BaselineT2LeftSegmentationJson=$(jq -s -r --argjson AlohaArgFlag '"-t"' --argjson Atlas '"ASHS-PMC-T2"' --argjson Handedness '"Left"' -f alohaFindSegmentFiles.jq "$BaselineJobsJsonFile")
+    BaselineT2LeftSegmentationJson=$( jq -r --argjson JobId "\"$BaselineAshsPmcT2JobId\"" 'select(._id == $JobId)' "$BaselineJobsJsonFile" | jq --argjson AlohaArgFlag '"-t"' -f alohaJob2FileIds.jq | jq --argjson Handedness '"Left"' '.Outputs[] | select(.FileModality == "SEG" and (.FileName | test("lfseg_heur")) and (.FileTags | any(. == $Handedness)) )' )
     if [ -z "$BaselineT2LeftSegmentationJson" ] || [ "$BaselineT2LeftSegmentationJson" = "null" ]
     then
-    	echo "${CmdName} : Missing baseline T2 Left segmentation file" 1>&2
-    	exit 8
+    	echo "${CmdName} : Missing baseline T2 Left Segmentation" 1>&2
+    	exit 4
     fi
-    
-    BaselineT2RightSegmentationJson=$(jq -s -r --argjson AlohaArgFlag '"-u"' --argjson Atlas '"ASHS-PMC-T2"' --argjson Handedness '"Right"' -f alohaFindSegmentFiles.jq "$BaselineJobsJsonFile")
+
+    BaselineT2RightSegmentationJson=$( jq -r --argjson JobId "\"$BaselineAshsPmcT2JobId\"" 'select(._id == $JobId)' "$BaselineJobsJsonFile" | jq --argjson AlohaArgFlag '"-u"' -f alohaJob2FileIds.jq | jq --argjson Handedness '"Right"' '.Outputs[] | select(.FileModality == "SEG" and (.FileName | test("lfseg_heur")) and (.FileTags | any(. == $Handedness)) )' )    
     if [ -z "$BaselineT2RightSegmentationJson" ] || [ "$BaselineT2RightSegmentationJson" = "null" ]
     then
-    	echo "${CmdName} : Missing baseline T2 Right segmentation file" 1>&2
+    	echo "${CmdName} : Missing baseline T2 Right Segmentation" 1>&2
+    	exit 5
+    fi
+
+    BaselineT1NiftiTrimmedJson=$(jq -r --argjson JobId "\"$BaselineAshsPmcT2JobId\"" 'select(._id == $JobId)' "$BaselineJobsJsonFile" | jq --argjson AlohaArgFlag '"-b"'  -f alohaJob2FileIds.jq | jq -r --argjson ClassificationMeasurement '"T1"' '.Inputs[] | select( (.FileType == "nifti") and (.FileTags | any(. == "Trimmed")) and (.FileClassificationMeasurement | test($ClassificationMeasurement)) )')
+    if [ -z "$BaselineT1NiftiTrimmedJson" ] || [ "$BaselineT1NiftiTrimmedJson" = "null" ]
+    then
+    	echo "${CmdName} : Missing baseline T1 Nifti Trimmed input" 1>&2
+    	exit 6
+    fi
+
+    BaselineT2NiftiJson=$(jq -r --argjson JobId "\"$BaselineAshsPmcT2JobId\"" 'select(._id == $JobId)' "$BaselineJobsJsonFile" | jq --argjson AlohaArgFlag '"-c"' -f alohaJob2FileIds.jq | jq -r --argjson ClassificationMeasurement '"T2"' '.Inputs[] | select( (.FileType == "nifti")  and (.FileClassificationMeasurement | test($ClassificationMeasurement)) )' )
+    if [ -z "$BaselineT2NiftiJson" ] || [ "$BaselineT2NiftJson" = "null" ]
+    then
+    	echo "${CmdName} : Missing baseline T2 Nifti input" 1>&2
     	exit 7
     fi
+
+    BaselineAshsPmcT1JobId=$( jq  -s -r '[ .[] | select( (.gear_info.name == "ashs") and (.detail.state == "complete") and (.config.config.ASHS_Atlases == "ASHS-PMC-T1") ) ] | sort_by(.created) | last | ._id' "$BaselineJobsJsonFile")
+    if [ -z "$BaselineAshsPmcT1JobId" ] || [ "$BaselineAshsPmcT1JobId" = "null" ]
+    then
+    	echo "${CmdName} : Missing baseline ASHS-PMC-T1 job" 1>&2
+    	exit 8
+    fi
+
+    BaselineT1LeftSegmentationJson=$( jq -r --argjson JobId "\"$BaselineAshsPmcT1JobId\"" 'select(._id == $JobId)' "$BaselineJobsJsonFile" | jq --argjson AlohaArgFlag '"-r"' -f alohaJob2FileIds.jq | jq --argjson Handedness '"Left"' '.Outputs[] | select(.FileModality == "SEG" and (.FileName | test("lfseg_heur")) and (.FileTags | any(. == $Handedness)) )' )
+    if [ -z "$BaselineT1LeftSegmentationJson" ] || [ "$BaselineTLeftSegmentationJson" = "null" ]
+    then
+    	echo "${CmdName} : Missing baseline T1 Left Segmentation" 1>&2
+    	exit 9
+    fi
+
+    BaselineT1RightSegmentationJson=$( jq -r --argjson JobId "\"$BaselineAshsPmcT1JobId\"" 'select(._id == $JobId)' "$BaselineJobsJsonFile" | jq --argjson AlohaArgFlag '"-s"' -f alohaJob2FileIds.jq | jq --argjson Handedness '"Right"' '.Outputs[] | select(.FileModality == "SEG" and (.FileName | test("lfseg_heur")) and (.FileTags | any(. == $Handedness)) )' )
+    if [ -z "$BaselineT1RightSegmentationJson" ] || [ "$BaselineT1RightSegmentationJson" = "null" ]
+    then
+    	echo "${CmdName} : Missing baseline T1 Right Segmentation" 1>&2
+    	exit 10
+    fi
+
+
+fi
+
+
     
     #
     # Followup Session Info should include session data
@@ -164,8 +209,8 @@ then
     BaselineJsonFile="${TmpDir}/Baseline.json"
     jq -r -n	 --argjson JobInfo "$JobJson"							\
     		 --argjson Baseline "$BaselineJson"						\
-    		 --argjson BaselineT1 "$BaselineT1Json"						\
-      		 --argjson BaselineT2 "$BaselineT2Json"						\
+    		 --argjson BaselineT1 "$BaselineT1NiftiTrimmedJson"				\
+      		 --argjson BaselineT2 "$BaselineT2NiftiJson"					\
           	 --argjson BaselineT1LeftSegmentation "$BaselineT1LeftSegmentationJson" 	\
           	 --argjson BaselineT1RightSegmentation "$BaselineT1RightSegmentationJson" 	\
           	 --argjson BaselineT2LeftSegmentation "$BaselineT2LeftSegmentationJson" 	\
@@ -186,35 +231,131 @@ then
     FollowupsJsonFile="${TmpDir}/Followups.json"
     for FollowupSessionId in $(jq -r '.Followups[] | .SessionId' "$SortedSessionsJsonFile")
     do
+	#
+	# Single Followup Session
+	#
     	FollowupSessionJsonFile="${TmpDir}/FollowupSession.json"
     	jq -r '..|select(._id == "'"$FollowupSessionId"'")?' "$SubjectJsonFile" > "$FollowupSessionJsonFile"
-    	# *** should probably verify we have something
+	if [ -S "$FollowupSessionJsonFile" ]
+	then
+	    echo "${CmdName}: No followup session found" 1>&2
+	    exit 11
+	fi
+
+	#
+	# SessionId, SessionLabel, SessionScanDateTime
+	#
     	FollowupJson=$(jq -r -L "$FwLibDir" 'include "FwLib"; ..|select(._id == "'"$FollowupSessionId"'")? | ({"SessionId": ._id, "SessionLabel": .label, "SessionScanDateTime": sessionScanDateTime(.)})' "$SubjectJsonFile")
     
     	FollowupSessionLabel=$(echo "$FollowupJson" | jq -r '.SessionLabel')
         [ -n "$opt_v" ] && echo "FollowupSession = '${FollowupSessionLabel}(${FollowupSessionId})'" 1>&2
     
-    
-    	FollowupT1Json=$(jq -r --argjson AlohaArgFlag '"-f"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile")
-    	if [ -z "$FollowupT1Json" ] || [ "$FollowupT1Json" = "null" ]
-    	then
-    		echo "${CmdName} : followup session '$FollowupSessionLabel' ($FollowupSessionId) missing T1 acquisition.  Skipping." 1>&2
-    		FollowupT1Json='{"Missing": true}'
-    	fi
-    
-    	FollowupT2Json=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile")
-    	if [ -z "$FollowupT2Json" ] || [ "$FollowupT2Json" = "null" ]
-    	then
-    		echo "${CmdName} : followup session '$FollowupSessionLabel' ($FollowupSessionId) missing T2 acquisition.  Skipping." 1>&2
-    		FollowupT2Json='{"Missing": true}'
-    
-    	fi
-    
+    	FollowupT1NiftiTrimmedJson=$(jq -r --argjson AlohaArgFlag '"-f"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and (.FileTags | any(. == "Trimmed")) ) ')
+	if [ -z "$FollowupT1NiftiTrimmedJson" ]
+	then
+	    # Need to find the T1 Dicom AlohaInput for this session, if there is one
+	    # convert it to nifti, this may be redundant, but it only takes a moment
+	    # then trim the neck and rebuild the Followup Jobs/Session file ??
+	    # 
+	    FollowupT1DicomFileId=$(echo "$FollowupT1DicomJson" | jq -r '.FileId')
+	    FollowupT1NiftiFileId=$(jq -s --argjson InputFileId "\"$FollowupT1DicomFileId\"" --argjson GearName '"dcm2niix"' --argjson FileType '"nifti"' -r -f alohaInputFileId2JobOutputFileIds.jq "$FollowupJobsJsonFile")
+	    if [ -z "$FollowupT1NiftiFileId" ]
+	    then
+		if [ -n $opt_f ] && (echo "$opt_f" | grep -i -q "T1Dcm2Niix")
+		then
+		    FollowupT1Dicom2NiftiJobId=$FakeFollowupT1Dicom2NiftiJobId
+		else
+		    FollowupT1Dicom2NiftiJobId=$(sys fwRunGear -w -t "$GearTags" -g dcm2niix -i dcm2niix_input "$FollowupT1DicomFileId")
+		fi
+	 
+		FollowupT1NiftiFileId=$(fwget -1 -j "$FollowupT1Dicom2NiftiJobId" | jq -r '.outputs[] | select(.type == "nifti") | .file_id')
+		FollowupT1DicomTags=$(fwTag "$FollowupT1DicomFileId")
+
+    		sys fwfind -1 -j -r session="$FollowupSessionId" > "$FollowupJobsJsonTmpFile"
+    		if [ "$?" != 0 ]
+    		then
+    		    echo "${CmdName} : failed getting finding jobs for '$SessionLabel' ($SessionId)" 1>&2
+    		    exit 1
+    		fi
+		[ -s "$FollowupJobsJsonTmpFile" ] && mv "$FollowupJobsJsonTmpFile" "$FollowupJobsJsonFile"
+	 
+		echo "fwTag -t $FollowupT1DicomTags $FollowupT1NiftiFileId" | od -bc
+	    
+		# Set new nifti file to be an AlohaInput
+		[ -n "$FollowupT1DicomTags" ] && sys fwTag -t "$FollowupT1DicomTags" "$FollowupT1NiftiFileId"
+	    fi
+   
+	    FollowupT1NiftiTrimmedFileId=$(jq -s --argjson InputFileId "\"$FollowupT1NiftiFileId\"" --argjson GearName '"necktrim"' -r '[ .[] | select( (.gear_info.name == $GearName) and (.config.inputs[].object.file_id == $InputFileId) )] | sort_by(.created) | if (length > 0) then (last | [ .outputs[] | select(.type == "nifti")] | last | .file_id) else empty end ' "$FollowupJobsJsonFile")
+	    if [ -z "$FollowupT1NiftiTrimmedFileId" ]
+	    then
+		if [ -n $opt_f ] && (echo "$opt_f" | grep -i -q "T1Necktrim")
+		then
+		    FollowupT1NiftiTrimmedJobId="$FakeFollowupT1NiftiTrimmedJobId"
+		else
+		    FollowupT1NiftiTrimmedJobId=$(sys fwRunGear -w -t "$GearTags" -g necktrim -i file "$FollowupT1NiftiFileId")
+		fi
+
+		FollowupT1NiftiTrimmedFileId=$(fwget -1 -j "$FollowupT1NiftiTrimmedJobId" | jq -r '.outputs[] | select(.type == "nifti") | .file_id')
+		if [ -z "$FollowupT1NiftiTrimmedFileId" ]
+		then
+		    echo "${CmdName} : missing FollowupT1NiftiTrimmedFileId which really should have been there" 1>&2
+		    exit 2
+		fi
+
+    		sys fwfind -1 -j -r session="$FollowupSessionId" > "$FollowupJobsJsonTmpFile"
+    		if [ "$?" != 0 ]
+    		then
+    		    echo "${CmdName} : failed getting finding jobs for '$SessionLabel' ($SessionId)" 1>&2
+    		    exit 1
+    		fi
+		[ -s "$FollowupJobsJsonTmpFile" ] && mv "$FollowupJobsJsonTmpFile" "$FollowupJobsJsonFile"
+	    fi
+	    FollowupT1NiftiTrimmedJson=$(jq -r --argjson AlohaArgFlag '"-f"' --argjson ClassificationMeasurement '"T1"' -f alohaFindT1T2.jq "$FollowupSessionJsonFile" | jq -r 'select( (.FileType == "nifti") and (.FileTags | any(. == "Trimmed")) )'  )
+	fi
+
+    	FollowupT2NiftiJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile" | jq -r 'select( .FileType == "nifti" ) ')
+	if [ -z "$FollowupT2NiftiJsonx" ]
+	then
+    	    FollowupT2DicomJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile" | jq -r 'select( (.FileType == "archive") or (.FileType == "dicom") ) ')
+	    if [ -z "$FollowupT2DicomJson" ]
+	    then
+		echo "${CmdName} : Missing Followup T2 for ${FollowupSessionLabel}(${FollowupSessionId}). Skipping" 1>&2
+		FollowupT2NiftiJson='{ "Missing": true }'
+	    else
+		FollowupT2DicomFileId=$(echo "$FollowupT2DicomJson" | jq -r '.FileId')
+		FollowupT2Dicom2NiftiJobId=$(sys fwRunGear -w -t "$GearTags" -g dcm2niix -i dcm2niix_input "$FollowupT2DicomFileId")
+    		if [ "$?" != 0 ]
+    		then
+    		    echo "${CmdName} : fwRunGear failed fwRunGear -w -t '$GearTags' -g dcm2niix -i dcm2niix_input '$FollowupT2DicomFileId'" 1>&2
+    		    exit 1
+    		fi
+		
+		FollowupT2NiftiFileId=$(fwget -1 -j "$FollowupT2Dicom2NiftiJobId" | jq -r '.outputs[] | select(.type == "nifti") | .file_id')
+	    
+		FollowupT2DicomTags=$(fwTag "$FollowupT2DicomFileId")
+
+		#
+		# fwTag needs the -q to keep the tags from being added to the followup json
+		#
+		[ -n "$FollowupT2DicomTags" ] && sys fwTag -q -t "$FollowupT2DicomTags" "$FollowupT2NiftiFileId"
+
+		sys fwget -1 -raGz "$FollowupSessionId" > "$FollowupSessionJsonFile"
+
+		FollowupT2NiftiJson=$(jq -r --argjson AlohaArgFlag '"-g"' --argjson ClassificationMeasurement '"T2"' -f alohaFindT1T2.jq  "$FollowupSessionJsonFile" | jq -r 'select( .FileType == "nifti" ) ')
+	    fi
+	fi
+
     	jq -r -n --argjson Followup "$FollowupJson"				\
-    	      	 --argjson FollowupT1 "$FollowupT1Json"				\
-    	         --argjson FollowupT2 "$FollowupT2Json"				\
+    	      	 --argjson FollowupT1 "$FollowupT1NiftiTrimmedJson"		\
+    	         --argjson FollowupT2 "$FollowupT2NiftiJson"			\
+    		 '$Followup + {"T1": $FollowupT1, "T2": $FollowupT2}' >> /tmp/Aloha/FollowupsTrace.json
+
+    	jq -r -n --argjson Followup "$FollowupJson"				\
+    	      	 --argjson FollowupT1 "$FollowupT1NiftiTrimmedJson"		\
+    	         --argjson FollowupT2 "$FollowupT2NiftiJson"			\
     		 '$Followup + {"T1": $FollowupT1, "T2": $FollowupT2}'
-    done | jq -s '{"Followups": . }' > "$FollowupsJsonFile"
+
+    done | tee /tmp/trace |  jq -s '{"Followups": . }' > "$FollowupsJsonFile"
     
     jq -r -n --slurpfile Baseline "$BaselineJsonFile" --slurpfile Followups "$FollowupsJsonFile" '($Baseline[]) + ($Followups[])' > "$AlohaInputsJsonFile"
     
@@ -227,7 +368,8 @@ then
     then
         sys fwuploadfile -p "$SubjectId" "$AlohaInputsJsonFile"
     fi
-fi
+
+    exit
 
 FollowupDir="${TmpDir}/Followups"
 
@@ -238,11 +380,11 @@ then
     sys fwget -v -f --download --download-dir "$TmpDir" "$AlohaInputsJsonFileId"
 fi
 
-BaselineDir="${TmpDir}/Baseline"
-[ -e "$BaselineDir" ] || sys mkdir "$BaselineDir"
-
 BaselineJsonFile="${TmpDir}/Baseline.json"
-jq -r '.Baseline' "$AlohaInputsJsonFile" > "$BaselineJsonFile"
+if [ -e "$AlohaInputsJsonFile" ] && [ -s "$AlohaInputsJsonFile" ]
+then
+    jq -r '.Baseline' "$AlohaInputsJsonFile" > "$BaselineJsonFile"
+fi
 
 DownloadedAllFiles=true
 if [ -n "$opt_d" ]
@@ -287,6 +429,8 @@ then
 
 	BaselineSessionScanDateTime=$(jq -r '.Baseline.SessionScanDateTime' "$AlohaInputsJsonFile")
 	BaselineSessionScanDate=$(date -d "$BaselineScanDateTime" "+%Y-%m-%d")
+
+	# *** Should verify aspect ratios for T1/T2 are acceptable
 
 	#skip the session info keys
 	for k in $(jq -r '.Baseline | keys[] as $k | select((.[$k]|type) == "object") | $k' "$AlohaInputsJsonFile")
@@ -383,8 +527,6 @@ then
 	    else
 		echo "${CmdName} : Invalid session aloha arguments for '${FollowupSessionLabel}(${FollowupSessionId})'. Skipping" 1>&2
 	    fi
-# ***
-exit
 	done
 fi
 
